### ISSUE TITLE
Driver Signing Windows 10 Not Test Mode 

### ISSUE THREAD

**Issue by MabezDev** [sk1080/nvidia-kvm-patcher#12]
Awesome work so far.

It patches fine and works great but one of the games I play (PUBG) won't let me launch in test mode. When I manually disable driver signing in safe mode menu It works but as far as I know there isn't a permanent way to disable it. The cert's install fine btw.

Any ideas?

**Comment by sk1080** [comment]
Only alternative I can recommend is using libvirt+qemu as your virtualization and using their workaround (see README).

**Comment by MabezDev** [comment]
That is the original solution I was using, sadly I'm running a Ryzen system and my performance gets shafted by the kvm npt bug. Oh well.

**Comment by sk1080** [comment]
You might want to consider looking at what the game cheats kids are doing these days to bypass driver signing. Afaik, they have some sort of a system where they load a vulnerable signed driver, pwn it, and then load their unsigned stuff. However, the method would probably require a decent amount of adaptation to get it working for a graphics driver...
