### ISSUE TITLE
Does it work on 372.70?

### ISSUE THREAD

**Issue by kevinlekiller** [sk1080/nvidia-kvm-patcher#2]
Not tried it myself, still on 372.54

Thanks for the work on this.

**Comment by sk1080** [comment]
Seems to, at least with the powershell version of the patcher which does a more generic search. Chances are, unless they "introduce some additional bugs", as long as the power shell version of the patcher doesn't complain about not finding the patch pattern, it should work.

**Comment by kevinlekiller** [comment]
Thanks, will give it a go.

**Comment by kevinlekiller** [comment]
Installed and running good, thanks.
