### ISSUE TITLE
gtx680, unraid, still error 43

### ISSUE THREAD

**Issue by peacememories** [sk1080/nvidia-kvm-patcher#20]
Hello, and thank you for writing this patcher.

Unfortunately I haven't gotten it to work properly so far. I followed the instructions, even added the kvm hidden property and tried to enable MSI, but the error 43 still persists.

GPU:
Zotac GTX 680 amp
driver: 391.24

System:
unRaid 6.5
qemu 2.11.1
libvirt 4.0.0

VM settings:
ovmf
bios: Q35-2.11
GTX680 added as secondary gpu with vnc gpu as first.

I have no idea what could be amiss except for maybe my hardware not being compatible (but the gpu passthrough works fine with an ubuntu guest so I don't know).
MSI does not seem to be active even with the MSISupported DWORD added in the registry.

**Comment by dobromyslov** [comment]
Yesterday I bought the same video adapter Gigabyte GTX680 and fixed the same issue.

Root cause: your video card firmware does not support UEFI ovmf.

Solution: update GTX680 firmware to this one : https://www.techpowerup.com/vgabios/154688/154688
Firmware version 80.04.47.00.84
UEFI Supported: Yes

Steps:
1. Download nvflash for Linux: https://www.techpowerup.com/download/nvidia-nvflash/
2. Download firmware 80.04.47.00.84 from here https://www.techpowerup.com/vgabios/154688/154688
3. Run 
`./nvflash_linux -6 GTX680-BIOS-UEFI-80.04.47.00.84.rom`

And then press Y two times.
My output:

> NVIDIA Firmware Update Utility (Version 5.414.0)
> Simplified Version For OEM Only
> Checking for matches between display adapter(s) and image(s)...
>  
> Adapter: GeForce GTX 680      (10DE,1180,1458,353C) H:--:NRM  S:00,B:02,D:00,F:00
>  
> WARNING: Firmware image PCI Subsystem ID (1458.353D)
>   does not match adapter PCI Subsystem ID (1458.353C).
>  
> Please press 'y' to confirm override of PCI Subsystem ID's:  y
> Overriding PCI subsystem ID mismatch
> Current      - Version:80.04.47.00.11 ID:10DE:1180:1458:353C
>                GK104 Board - 20020000 (Normal Board)
> Replace with - Version:80.04.47.00.84 ID:10DE:1180:1458:353D
>                GK104 Board - 20020000 (Normal Board)
>  
> Update display adapter firmware?
> Press 'y' to confirm (any other key to abort):  y
> Identifying EEPROM...
> EEPROM ID (C8,4012) : GD GD25Q20 2.7-3.6V 2048Kx1S, page
> Storing updated firmware image...
> .........................................
> Verifying update...
> Update successful.
>  
> Firmware image has been updated from version 80.04.47.00.11 to 80.04.47.00.84.
>  
>  
> A reboot is required for the update to take effect.

After the firmware update use settings like this:

> <domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
>   <name>win10</name>
>   <uuid>437b12cd-a1bd-4ee9-bd51-14f5583290dc</uuid>
>   <memory unit='KiB'>8388608</memory>
>   <currentMemory unit='KiB'>8388608</currentMemory>
>   <vcpu placement='static'>4</vcpu>
>   <cputune>
>     <vcpupin vcpu='0' cpuset='4'/>
>     <vcpupin vcpu='1' cpuset='5'/>
>     <vcpupin vcpu='2' cpuset='6'/>
>     <vcpupin vcpu='3' cpuset='7'/>
>   </cputune>
>   <os>
>     <type arch='x86_64' machine='pc-i440fx-2.10'>hvm</type>
>     <loader readonly='yes' type='pflash'>/usr/share/edk2-ovmf/OVMF_CODE.fd</loader>
>     <nvram>/var/lib/libvirt/qemu/nvram/win10_VARS.fd</nvram>
>     <bootmenu enable='no'/>
>   </os>
>   <features>
>     <acpi/>
>     <apic/>
>     <hyperv>
>       <relaxed state='on'/>
>       <vapic state='on'/>
>       <spinlocks state='on' retries='8191'/>
>       <vendor_id state='on' value='Nvidia43FIX'/>
>     </hyperv>
>     <kvm>
>       <hidden state='on'/>
>     </kvm>
>     <vmport state='off'/>
>   </features>
>   <cpu mode='host-passthrough' check='none'>
>     <topology sockets='1' cores='2' threads='2'/>
>   </cpu>
>   <clock offset='localtime'>
>     <timer name='rtc' tickpolicy='catchup'/>
>     <timer name='pit' tickpolicy='delay'/>
>     <timer name='hpet' present='no'/>
>     <timer name='hypervclock' present='yes'/>
>   </clock>
> 

Required are:
1. <vendor_id state='on' value='Nvidia43FIX'/>
2. <kvm>
      <hidden state='on'/>
   </kvm>

**Comment by dobromyslov** [comment]
And use UEFI OVMF BIOS with your libvirt.

Then remove VNC or Spice and VGA cards.
And add your host PCI GPU to the virtual machine.
Connect your monitor HDMI/DVI/VGA to the GTX680.
Run the VM and you'll see the boot process prior to Windows loading.

**Comment by dobromyslov** [comment]
And I should add that there is no need to use this patch if you change vendor id and hide KVM in your VM settings as I mentioned.

**Comment by psy0rz** [comment]
I can confirm this works: I have a MSI GTX660 (model N660 TF 2GD5/OC ) and i also flashed new UEFI firmware.

I tried all other options a gazillion times, so thanks for this!

Now i can use Fusion 360 with a spacemouse from my linux workstation. :D

**Comment by dobromyslov** [comment]
Yep. I also aquired Aten CS692 KVM and  can now switch fast one of my
displays and mouse+keyboard between linux and windows just using
scroll+scroll+enter.

Also I tunned sound forwarding from windows guest to linux host with
PulseAudio. Dreams come true:)

**Comment by peacememories** [comment]
After the typical "turning it off and on again" routine a few days later I got my gtx680 to work with windows as well (although performance got immediately trashed if I connected a second monitor). I don't have my test setup right now and my gtx680 kicked the bucket a while after, so I'll close this issue if that's alright. Thanks for the hints :)
