### ISSUE TITLE
what about a fix for ubuntu on Hyper-V?

### ISSUE THREAD

**Issue by wiwengweng** [sk1080/nvidia-kvm-patcher#28]
Hi, this works great for my Win10 VM on Hyper-V, Thank you.

But If I want a Ubuntu 16.04 VM on Hyper-V, I will still get a error when install the nvidia driver. Is there a fix  for Ubuntu then?

TIA.

**Comment by rlewkowicz** [comment]
@wiwengweng What errors are you getting? I was able to install the driver in headless mode and use the native hyperv window. I get an nvidia-smi error about not being able to get a handle for the graphics card.
