### ISSUE TITLE
Add another path to $inf2cat_paths

### ISSUE THREAD

**Issue by sakishrist** [sk1080/nvidia-kvm-patcher#31]
Please add the following path to that variable as well. For me, this was the location of that file.

```
C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/Inf2Cat.exe
```

**Comment by sk1080** [comment]
added:
https://github.com/sk1080/nvidia-kvm-patcher/commit/ef89d0b9b4e8d284c6ee02c660a167dbe500390b
