### ISSUE TITLE
Error: Cannot find path '\CurrentUser\PrivateCertStore' because it does not exist.

### ISSUE THREAD

**Issue by T-vK** [sk1080/nvidia-kvm-patcher#33]
I got an error trying to patch 417.01 for the GTX 1060 Mobile with Max-Q Design:

I'm on Windows 10 pro. 
I ran a powershell as administrator and executed the script as descriped in the Readme. Here is the result:

```
Certificate Path:  C:\Users\Admin\Desktop\nvidia-kvm-patcher-master\TestSign.cer
Get-ChildItem : Cannot find path '\CurrentUser\PrivateCertStore' because it does not exist.
At C:\Users\Admin\Desktop\nvidia-kvm-patcher-master\gencert.ps1:50 char:9
+ $Cert = Get-ChildItem Cert:\CurrentUser\PrivateCertStore | Where {$_. ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\CurrentUser\PrivateCertStore:String) [Get-ChildItem], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Cert Not Found in Root Store
Certificate not Found in User Store, Creating
Adding Certificate to Root Store
    [+] Signing Catalog File
The following certificate was selected:
    Issued to: SKSoftware
    Issued by: SKSoftware
    Expires:   Wed Dec 04 08:54:34 2019
    SHA1 hash: 78CE60FA3EDB26CEE5612AEBB0760648B5A62BAB

Done Adding Additional Store
Successfully signed: C:\NVIDIA\DisplayDriver\417.01\Win10_64\International\Display.Driver./nv_disp.cat

Number of files successfully Signed: 1
Number of warnings: 0
Number of errors: 0
The following certificate was selected:
    Issued to: SKSoftware
    Issued by: SKSoftware
    Expires:   Wed Dec 04 08:54:34 2019
    SHA1 hash: 78CE60FA3EDB26CEE5612AEBB0760648B5A62BAB

Done Adding Additional Store
Successfully signed: C:\NVIDIA\DisplayDriver\417.01\Win10_64\International\Display.Driver\nvlddmkm.sys

Number of files successfully Signed: 1
Number of warnings: 0
Number of errors: 0
```

In order to run the powershell script I had to run `Set-ExecutionPolicy Unrestricted` first! Otherwise Windows wouldn't let me run it.

Trying to run `C:\NVIDIA\DisplayDriver\417.01\Win10_64\International\setup.exe` results in an error message:
Windows cannot access the specified device, patch or file. You may not have the appropriate permissions to access the item. 

Running it as administrator results in the same message.

**Comment by fcadet01** [comment]
Got the same error.

**Comment by sk1080** [comment]
This error shouldn't be fatal, but I just fixed it. As for the second part, I noticed the newer installers like to delete themselves. Try duping the installer before closing the initial instance. I just retested on 419.67 and everything seems to be working, reopen if there is an issue. 
https://github.com/sk1080/nvidia-kvm-patcher/commit/0a3a68549fb373fcf4326aa04948853e44fcde97
