### ISSUE TITLE
Video_TDR_Failure (nvlddmkm.sys)

### ISSUE THREAD

**Issue by lilrags16** [sk1080/nvidia-kvm-patcher#35]
I know this is intended for KVM, but I was told that it might work for ESXi. Blue Screens after login.

**Comment by sk1080** [comment]
This sounds like an issue likely unrelated to the patch; Not all virtualization systems meet the bios/timing/memory/? requirements for a NVIDIA graphics card to function. Debugging complex issues in a binary graphics driver is honestly beyond my capability or current desire. 

Please reopen if you can trace this back to this patch or if you find out any additional info.
