### ISSUE TITLE
Does it works now?

### ISSUE THREAD

**Issue by luxflow** [sk1080/nvidia-kvm-patcher#7]
hi @sk1080
first of all thanks for your work for kvm. 

I've tried this patch on windows 10 to nvidia 327.20 from nvidia official site

but I'm stucked in stage 6
> 6. Install Driver Through Extracted Installer (In C:/NVIDIA/DisplayDriver/Version)

I didn't click any next button in nvidia installer, closes nvidia install in step 1

whenever I try to install, it raise error installer failed (see below, but in my case no items in list)
![rkoi8r9](https://cloud.githubusercontent.com/assets/10526492/24809435/7f47dd66-1bfa-11e7-926c-f1f3871ed253.png)

it seems nvidia check file integrity, any ideas?

**Comment by lifespirit** [comment]
Driver work only with  Versions 361.91, 368.39, and 372.54. Use 372.54, not 327.20.

**Comment by sk1080** [comment]
Should cover a wider range of drivers now, tested up to 384.76. However, 327.20 probably isn't supported, and probably never will be (its pretty old). So, I guess it works now? Closing the issue.
