### ISSUE TITLE
Latest Drivers?

### ISSUE THREAD

**Issue by sshaikh** [sk1080/nvidia-kvm-patcher#8]
I just tried the script with 381.65 and got the following:

[+] Unpacking nvlddmkm.sys
[+] Patching CPUID Check
[!] Failure: 0 occurrences of patch pattern found

So I presume the search string has changed. Do we know the latest version which the patcher does work with?

**Comment by sk1080** [comment]
I haven't used it myself it a while, so I don't know when it broke. After trying various virtualization solutions and getting some disappointing results, I ended up sticking with libvirt/kvm/qemu, which of course has the workaround available. If I get around to it ill see what changed.

**Comment by sshaikh** [comment]
If anyone is interested I went through them all and the last version that the patcher has a success message with is:

GeForce Game Ready Driver WHQL	376.33	December 14, 2016

Having said that, it still didnt work with my set up (XenServer W10 x64) - still code 34.

**Comment by sk1080** [comment]
Code 34? or Code 43? Also check to make sure your card is in MSI mode, and if that fails, make sure you are using bios on xen and not ovmf.

**Comment by sshaikh** [comment]
Good call wrt KVM. I spent a couple of hours setting up the passing through of the card to a Proxmox VM and it works perfectly, with no hacking on the guest. Recommended for those who have the option.
