### ISSUE TITLE
Proxmox 5 (beta) host, Win10 Insider Preview BSODS after bcdedit

### ISSUE THREAD

**Issue by tymanthius** [sk1080/nvidia-kvm-patcher#9]
After running bcdedit to turn off driver signing in this envrionment, the screen does the Win10 version of BSOD and won't boot into windows.  :(

Can't find a way to recover either, so have to reload the whole Win10 OS

**Comment by sk1080** [comment]
Could always just edit the BCD from the windows install media using cmd.

Im going to go ahead and close this, as while this issue may prevent this software from being used, it isn't exactly an issue with the software itself. Might be best to ask elsewhere what might be going on.
